name: CI

on:
  push:
    branches:
      - main
      - task-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.11

    - name: Set up Python
      uses: actions/setup-python@v3.11
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

